// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTseQgh5YN32tkfhSNZ-V1sVkb89-WXZI',
    appId: '1:393975178236:web:b108f802ed4178b3708879',
    messagingSenderId: '393975178236',
    projectId: 'classmates1project',
    authDomain: 'classmates1project.firebaseapp.com',
    storageBucket: 'classmates1project.firebasestorage.app',
    measurementId: 'G-BVS3RMKH25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_g6l7391WNNJt5md5WMhTICjXIgJH2Rs',
    appId: '1:393975178236:android:6a547067cb896cfe708879',
    messagingSenderId: '393975178236',
    projectId: 'classmates1project',
    storageBucket: 'classmates1project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1dQYHHz67ImwKuHritjdG_K0DG5PyAk',
    appId: '1:393975178236:ios:084ef3b5bfe9f91d708879',
    messagingSenderId: '393975178236',
    projectId: 'classmates1project',
    storageBucket: 'classmates1project.firebasestorage.app',
    iosBundleId: 'com.example.classmateApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1dQYHHz67ImwKuHritjdG_K0DG5PyAk',
    appId: '1:393975178236:ios:084ef3b5bfe9f91d708879',
    messagingSenderId: '393975178236',
    projectId: 'classmates1project',
    storageBucket: 'classmates1project.firebasestorage.app',
    iosBundleId: 'com.example.classmateApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTseQgh5YN32tkfhSNZ-V1sVkb89-WXZI',
    appId: '1:393975178236:web:3d9d5ef851089c6e708879',
    messagingSenderId: '393975178236',
    projectId: 'classmates1project',
    authDomain: 'classmates1project.firebaseapp.com',
    storageBucket: 'classmates1project.firebasestorage.app',
    measurementId: 'G-Z9YGG5177L',
  );
}
