import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(result != null, 'No AppLocalizations found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'Classmate',
      'continue': 'Continue',
      'welcome_back': 'Welcome back',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'signup_prompt': "Don't have an account? Sign Up",
      'create_account': 'Create your account',
      'full_name': 'Full Name',
      'sign_up': 'Sign Up',
      'signup_successful': 'Signup Successful',
      'updates': 'Updates',
      'calls': 'Calls',
      'communities': 'Communities',
      'chats': 'Chats',
      'you': 'You',
      'direct_messages': 'Direct Messages',
      'search_chats_hint': 'Search chats by name...',
      'clear': 'Clear',
      'new_group': 'New group',
      'settings': 'Settings',
      'no_chats_yet': 'No chats yet. Tap + to start one.',
      'you_cannot_chat_with_yourself': 'You cannot chat with yourself.',
      'could_not_create_chat': 'Could not create chat: {{error}}',
      'search_user': 'Search User',
      'search_by_name_or_username': 'Search by name or username',
      'no_users_available': 'No users available.',
      'no_matching_users_found': 'No matching users found.',
      'profile': 'Profile',
      'user_not_found': 'User not found',
      'online': 'Online',
      'offline': 'Offline',
      'last_seen': 'Last seen {{time}}',
      'contact_information': 'Contact Information',
      'send_message': 'Send Message',
      'settings_account': 'Account',
      'not_available': 'Not available',
      'edit_profile': 'Edit Profile',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'receive_message_notifications': 'Receive message notifications',
      'sound': 'Sound',
      'play_notification_sound': 'Play notification sound',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'select_theme': 'Select Theme',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'select_language': 'Select Language',
      'privacy': 'Privacy',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'message_read': 'Message Read',
      'read_receipt': 'Read receipt:',
      'close': 'Close',
      'back': 'Back',
      'delete': 'Delete',
      'delete_for_me': 'Delete for me',
      'delete_for_everyone': 'Delete for everyone',
      'message_deleted': 'Message deleted',
      'star': 'Star',
      'unstar': 'Unstar',
      'message_options': 'Message options',
      'failed_to_send_message': 'Failed to send message: {{error}}',
      'failed_to_send_image': 'Failed to send image: {{error}}',
      'direct_message': 'Direct Message',
      'typing': 'typing...',
      'type_a_message': 'Type a message...',
      'error': 'Error: {{error}}',
      'please_sign_in_view_messages': 'Please sign in to view messages.',
      'no_messages_yet': 'No messages yet.',
      'no_messages_start': 'No messages yet. Start the conversation.',
      'call_ended': 'Call ended',
      'no_phone_number_found': 'No phone number found for this contact',
      'opening_dialer_for': 'Opening dialer for {{phone}}',
      'could_not_open_dialer': 'Could not open the dialer',
      'new_group_title': 'New Group',
      'add_members': 'Add members',
      'create_group': 'Create Group',
      'group_name_empty': 'Group name cannot be empty',
      'group_created': 'Group created',
      'failed_create_group': 'Failed to create group: {{error}}',
      'email_change_requested': 'Email change requested',
      'ok': 'OK',
      'profile_updated': 'Profile updated',
      'failed_save_profile': 'Failed to save profile: {{error}}',
      'profile_picture_updated': 'Profile picture updated successfully',
      'failed_upload_profile_picture': 'Failed to upload profile picture',
      'save': 'Save',
      'selected_language_changed': 'Language changed to {{language}}',
      'show_now': 'Show Now',
      'scheduled_in_5_seconds': 'Scheduled in 5 seconds',
      'schedule_5s': 'Schedule (5s)',
      'no_users_to_call': 'No other users to call',
      'select_contact_to_call': 'Select Contact to Call',
      'no_users_found': 'No users found',
      'something_went_wrong': 'Something went wrong',
      'classmate': 'Classmate',
      'recent_notifications': 'Recent Notifications',
      'title': 'Title',
      'body': 'Body',
      'just_now': 'Just now',
      'unknown_user': 'Unknown User',
      'no_phone_number_added': 'No phone number added',
      'phone': 'Phone',
      'call_with': 'Call with {{name}}',
      'end_call': 'End Call',
      'open_dialer': 'Open Dialer',
      'opens_phone_dialer_using_saved_contact':
          'This opens the phone dialer using the saved contact number.',
      'email_change_info':
          'We saved your requested email. To complete an email change you may need to re-authenticate (sign out and sign in) or perform the change from your account settings.',
      'communities_placeholder': 'Communities placeholder',
      'username': 'Username',
      'username_validation_error':
          'Username can only use letters, numbers, and underscores. Underscores cannot be first or last.',
      'username_login_firestore_error':
          'Username login needs Firestore read access. Temporarily log in with email, or update rules for username lookup.',
    },
    'es': {
      'app_name': 'Classmate',
      'continue': 'Continuar',
      'welcome_back': 'Bienvenido de nuevo',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'login': 'Iniciar sesión',
      'signup_prompt': '¿No tienes una cuenta? Regístrate',
      'create_account': 'Crea tu cuenta',
      'full_name': 'Nombre completo',
      'sign_up': 'Regístrate',
      'signup_successful': 'Registro exitoso',
      'updates': 'Actualizaciones',
      'calls': 'Llamadas',
      'communities': 'Comunidades',
      'chats': 'Chats',
      'you': 'Tú',
      'direct_messages': 'Mensajes Directos',
      'search_chats_hint': 'Buscar chats por nombre...',
      'clear': 'Borrar',
      'new_group': 'Nuevo grupo',
      'settings': 'Ajustes',
      'no_chats_yet': 'No hay chats. Pulsa + para empezar uno.',
      'you_cannot_chat_with_yourself': 'No puedes chatear contigo mismo.',
      'could_not_create_chat': 'No se pudo crear el chat: {{error}}',
      'search_user': 'Buscar usuario',
      'search_by_name_or_username': 'Buscar por nombre o usuario',
      'no_users_available': 'No hay usuarios disponibles.',
      'no_matching_users_found': 'No se encontraron usuarios coincidentes.',
      'profile': 'Perfil',
      'user_not_found': 'Usuario no encontrado',
      'online': 'En línea',
      'offline': 'Sin conexión',
      'last_seen': 'Última vez {{time}}',
      'contact_information': 'Información de contacto',
      'send_message': 'Enviar mensaje',
      'settings_account': 'Cuenta',
      'not_available': 'No disponible',
      'edit_profile': 'Editar perfil',
      'notifications': 'Notificaciones',
      'enable_notifications': 'Activar notificaciones',
      'receive_message_notifications': 'Recibir notificaciones de mensajes',
      'sound': 'Sonido',
      'play_notification_sound': 'Reproducir sonido de notificación',
      'appearance': 'Apariencia',
      'theme': 'Tema',
      'select_theme': 'Seleccionar tema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',
      'privacy': 'Privacidad',
      'privacy_policy': 'Política de privacidad',
      'terms_of_service': 'Términos de servicio',
      'logout': 'Cerrar sesión',
      'logout_confirm': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'message_read': 'Mensaje leído',
      'read_receipt': 'Recibo de lectura:',
      'close': 'Cerrar',
      'back': 'Atrás',
      'delete': 'Eliminar',
      'delete_for_me': 'Eliminar para mí',
      'delete_for_everyone': 'Eliminar para todos',
      'message_deleted': 'Mensaje eliminado',
      'star': 'Favorito',
      'unstar': 'Quitar favorito',
      'message_options': 'Opciones de mensaje',
      'failed_to_send_message': 'No se pudo enviar el mensaje: {{error}}',
      'failed_to_send_image': 'No se pudo enviar la imagen: {{error}}',
      'direct_message': 'Mensaje directo',
      'typing': 'escribiendo...',
      'type_a_message': 'Escribe un mensaje...',
      'error': 'Error: {{error}}',
      'please_sign_in_view_messages':
          'Por favor inicia sesión para ver los mensajes.',
      'no_messages_yet': 'Sin mensajes aún.',
      'no_messages_start': 'Sin mensajes aún. Empieza la conversación.',
      'call_ended': 'Llamada finalizada',
      'no_phone_number_found':
          'No se encontró número telefónico para este contacto',
      'opening_dialer_for': 'Abriendo marcador para {{phone}}',
      'could_not_open_dialer': 'No se pudo abrir el marcador',
      'new_group_title': 'Nuevo grupo',
      'add_members': 'Agregar miembros',
      'create_group': 'Crear grupo',
      'group_name_empty': 'El nombre del grupo no puede estar vacío',
      'group_created': 'Grupo creado',
      'failed_create_group': 'Error al crear el grupo: {{error}}',
      'email_change_requested': 'Cambio de correo solicitado',
      'ok': 'OK',
      'profile_updated': 'Perfil actualizado',
      'failed_save_profile': 'Error al guardar perfil: {{error}}',
      'profile_picture_updated': 'Foto de perfil actualizada con éxito',
      'failed_upload_profile_picture': 'Error al subir la foto de perfil',
      'save': 'Guardar',
      'selected_language_changed': 'Idioma cambiado a {{language}}',
      'show_now': 'Mostrar ahora',
      'scheduled_in_5_seconds': 'Programado en 5 segundos',
      'schedule_5s': 'Programar (5s)',
      'no_users_to_call': 'No hay otros usuarios para llamar',
      'select_contact_to_call': 'Seleccionar contacto para llamar',
      'no_users_found': 'No se encontraron usuarios',
      'something_went_wrong': 'Algo salió mal',
      'classmate': 'Classmate',
      'recent_notifications': 'Notificaciones recientes',
      'title': 'Título',
      'body': 'Cuerpo',
      'just_now': 'Hace poco',
      'unknown_user': 'Usuario desconocido',
      'no_phone_number_added': 'Sin número de teléfono añadido',
      'phone': 'Teléfono',
      'call_with': 'Llamada con {{name}}',
      'end_call': 'Finalizar llamada',
      'open_dialer': 'Abrir marcador',
      'opens_phone_dialer_using_saved_contact':
          'Abre el marcador telefónico usando el número de contacto guardado.',
      'email_change_info':
          'Hemos guardado el correo solicitado. Para completar un cambio de correo, puede que necesites re-autenticarte (cerrar y volver a iniciar sesión) o realizar el cambio desde tu configuración de cuenta.',
      'communities_placeholder': 'Placeholder de comunidades',
      'username': 'Nombre de usuario',
      'username_validation_error':
          'El nombre de usuario solo puede usar letras, números y guiones bajos. Los guiones bajos no pueden estar al principio ni al final.',
      'username_login_firestore_error':
          'El inicio de sesión con nombre de usuario necesita acceso de lectura a Firestore. Inicia sesión temporalmente con correo electrónico o actualiza las reglas para la búsqueda de nombre de usuario.',
    },
    'zh': {
      'app_name': 'Classmate',
      'feed': '动态',
      'calls': '通话',
      'communities': '社区',
      'chats': '聊天',
      'you': '你',
      'continue': '继续',
      'welcome_back': '欢迎回来',
      'email': '电子邮件',
      'password': '密码',
      'login': '登录',
      'signup_prompt': '还没有账户？注册',
      'create_account': '创建你的账户',
      'full_name': '全名',
      'sign_up': '注册',
      'settings': '设置',
      'new_group': '新群组',
      'search_user': '搜索用户',
      'search_by_name_or_username': '按姓名或用户名搜索',
      'search_chats_hint': '按名称搜索聊天...',
      'direct_messages': '直接消息',
      'clear': '清除',
      'no_chats_yet': '还没有聊天。点击 + 开始一个。',
      'no_users_available': '没有可用用户。',
      'no_matching_users_found': '没有找到匹配的用户。',
      'settings_account': '账户',
      'not_available': '不可用',
      'edit_profile': '编辑资料',
      'notifications': '通知',
      'enable_notifications': '启用通知',
      'receive_message_notifications': '接收消息通知',
      'sound': '声音',
      'play_notification_sound': '播放通知声音',
      'appearance': '外观',
      'theme': '主题',
      'select_theme': '选择主题',
      'light': '浅色',
      'dark': '深色',
      'language': '语言',
      'select_language': '选择语言',
      'privacy': '隐私',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'logout': '退出登录',
      'logout_confirm': '确定要退出登录吗？',
      'cancel': '取消',
      'profile': '个人资料',
      'user_not_found': '未找到用户',
      'online': '在线',
      'offline': '离线',
      'last_seen': '上次在线 {{time}}',
      'contact_information': '联系信息',
      'send_message': '发送消息',
      'call_ended': '通话已结束',
      'no_phone_number_found': '此联系人未找到电话号码',
      'opening_dialer_for': '正在打开拨号器拨打 {{phone}}',
      'could_not_open_dialer': '无法打开拨号器',
      'no_users_to_call': '没有其他用户可以调用',
      'select_contact_to_call': '选择要呼叫的联系人',
      'unknown_user': '未知用户',
      'no_phone_number_added': '未添加电话号码',
      'phone': '电话',
      'call_with': '与 {{name}} 通话',
      'end_call': '结束通话',
      'open_dialer': '打开拨号器',
      'opens_phone_dialer_using_saved_contact': '这将使用保存的联系人号码打开电话拨号器。',
      'save': '保存',
      'selected_language_changed': '语言已切换为 {{language}}',
    },
    'hi': {
      'app_name': 'Classmate',
      'feed': 'फीड',
      'calls': 'कॉल',
      'communities': 'समुदाय',
      'chats': 'चैट',
      'you': 'आप',
      'continue': 'जारी रखें',
      'welcome_back': 'वापसी पर स्वागत है',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'login': 'लॉगिन करें',
      'signup_prompt': 'खाता नहीं है? साइन अप करें',
      'create_account': 'अपना खाता बनाएं',
      'full_name': 'पूरा नाम',
      'sign_up': 'साइन अप करें',
      'signup_successful': 'साइन अप सफल',
      'updates': 'अपडेट',
      'settings': 'सेटिंग्स',
      'new_group': 'नया समूह',
      'search_user': 'उपयोगकर्ता खोजें',
      'search_by_name_or_username': 'नाम या उपयोगकर्ता नाम से खोजें',
      'search_chats_hint': 'नाम से चैट खोजें...',
      'direct_messages': 'सीधे संदेश',
      'clear': 'साफ करें',
      'no_chats_yet': 'अभी तक कोई चैट नहीं। शुरू करने के लिए + टैप करें।',
      'you_cannot_chat_with_yourself': 'आप अपने आप से चैट नहीं कर सकते।',
      'could_not_create_chat': 'चैट नहीं बना सके: {{error}}',
      'no_users_available': 'कोई उपयोगकर्ता उपलब्ध नहीं।',
      'no_matching_users_found': 'कोई मेल खाने वाले उपयोगकर्ता नहीं मिले।',
      'settings_account': 'खाता',
      'not_available': 'उपलब्ध नहीं',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'receive_message_notifications': 'संदेश सूचनाएं प्राप्त करें',
      'sound': 'ध्वनि',
      'play_notification_sound': 'सूचना ध्वनि चलाएं',
      'appearance': 'दिखावट',
      'theme': 'थीम',
      'select_theme': 'थीम चुनें',
      'light': 'हल्का',
      'dark': 'गहरा',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'privacy': 'गोपनीयता',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_service': 'सेवा की शर्तें',
      'logout': 'लॉगआउट करें',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'profile': 'प्रोफ़ाइल',
      'user_not_found': 'उपयोगकर्ता नहीं मिला',
      'online': 'ऑनलाइन',
      'offline': 'ऑफ़लाइन',
      'last_seen': 'आखिरी बार {{time}} को देखा गया',
      'contact_information': 'संपर्क जानकारी',
      'send_message': 'संदेश भेजें',
      'message_read': 'संदेश पढ़ा गया',
      'read_receipt': 'पढ़ने की रसीद:',
      'close': 'बंद करें',
      'back': 'पीछे',
      'delete': 'हटाएं',
      'delete_for_me': 'मेरे लिए हटाएं',
      'delete_for_everyone': 'सभी के लिए हटाएं',
      'message_deleted': 'संदेश हटाया गया',
      'star': 'पसंद करें',
      'unstar': 'पसंद न करें',
      'message_options': 'संदेश विकल्प',
      'failed_to_send_message': 'संदेश भेजने में विफल: {{error}}',
      'failed_to_send_image': 'छवि भेजने में विफल: {{error}}',
      'direct_message': 'सीधा संदेश',
      'typing': 'टाइप कर रहा है...',
      'type_a_message': 'संदेश लिखें...',
      'error': 'त्रुटि: {{error}}',
      'please_sign_in_view_messages': 'संदेश देखने के लिए कृपया साइन इन करें।',
      'no_messages_yet': 'अभी तक कोई संदेश नहीं।',
      'no_messages_start': 'अभी तक कोई संदेश नहीं। बातचीत शुरू करें।',
      'call_ended': 'कॉल समाप्त हुई',
      'no_phone_number_found': 'इस संपर्क के लिए कोई फोन नंबर नहीं मिला',
      'opening_dialer_for': '{{phone}} के लिए डायलर खोल रहे हैं',
      'could_not_open_dialer': 'डायलर नहीं खोल सके',
      'new_group_title': 'नया समूह',
      'add_members': 'सदस्य जोड़ें',
      'create_group': 'समूह बनाएं',
      'group_name_empty': 'समूह का नाम खाली नहीं हो सकता',
      'group_created': 'समूह बनाया गया',
      'failed_create_group': 'समूह बनाने में विफल: {{error}}',
      'email_change_requested': 'ईमेल परिवर्तन का अनुरोध किया गया',
      'ok': 'ठीक है',
      'profile_updated': 'प्रोफ़ाइल अपडेट की गई',
      'failed_save_profile': 'प्रोफ़ाइल सहेजने में विफल: {{error}}',
      'profile_picture_updated': 'प्रोफ़ाइल चित्र सफलतापूर्वक अपडेट किया गया',
      'failed_upload_profile_picture': 'प्रोफ़ाइल चित्र अपलोड करने में विफल',
      'save': 'सहेजें',
      'selected_language_changed': 'भाषा {{language}} में बदली गई',
      'show_now': 'अभी दिखाएं',
      'scheduled_in_5_seconds': '5 सेकंड में शेड्यूल किया गया',
      'schedule_5s': 'शेड्यूल (5s)',
      'no_users_to_call': 'कॉल करने के लिए कोई अन्य उपयोगकर्ता नहीं',
      'select_contact_to_call': 'कॉल करने के लिए संपर्क चुनें',
      'no_users_found': 'कोई उपयोगकर्ता नहीं मिला',
      'something_went_wrong': 'कुछ गलत हो गया',
      'classmate': 'Classmate',
      'recent_notifications': 'हाल की सूचनाएं',
      'title': 'शीर्षक',
      'body': 'निकाय',
      'just_now': 'अभी ही',
      'unknown_user': 'अज्ञात उपयोगकर्ता',
      'no_phone_number_added': 'कोई फोन नंबर जोड़ा नहीं गया',
      'phone': 'फोन',
      'call_with': '{{name}} के साथ कॉल करें',
      'end_call': 'कॉल समाप्त करें',
      'open_dialer': 'डायलर खोलें',
      'opens_phone_dialer_using_saved_contact':
          'यह सहेजे गए संपर्क नंबर का उपयोग करके फोन डायलर खोलता है।',
      'email_change_info':
          'हमने आपके अनुरोधित ईमेल को सहेज लिया है। ईमेल परिवर्तन को पूरा करने के लिए आपको पुनः प्रमाणित करने की आवश्यकता हो सकती है (साइन आउट और साइन इन करें) या अपनी खाता सेटिंग्स से परिवर्तन करें।',
      'communities_placeholder': 'समुदाय प्लेसहोल्डर',
      'username': 'उपयोगकर्ता नाम',
      'username_validation_error':
          'उपयोगकर्ता नाम केवल अक्षर, संख्या और अंडरस्कोर का उपयोग कर सकता है। अंडरस्कोर पहला या आखिरी नहीं हो सकता।',
      'username_login_firestore_error':
          'उपयोगकर्ता नाम लॉगिन को Firestore पढ़ने की पहुंच की आवश्यकता है। अस्थायी रूप से ईमेल के साथ लॉगिन करें या उपयोगकर्ता नाम खोज के लिए नियम अपडेट करें।',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    final map = _values[locale.languageCode] ?? _values['en']!;
    var value = map[key] ?? _values['en']![key] ?? key;
    params?.forEach((param, replacement) {
      value = value.replaceAll('{{$param}}', replacement);
    });
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'es', 'zh', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
