import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(result != null, 'No AppLocalizations found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'Classmate',
      'continue': 'Continue',
      'welcome_back': 'Welcome back',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'signup_prompt': "Don't have an account? Sign Up",
      'create_account': 'Create your account',
      'full_name': 'Full Name',
      'sign_up': 'Sign Up',
      'signup_successful': 'Signup Successful',
      'updates': 'Updates',
      'calls': 'Calls',
      'communities': 'Communities',
      'chats': 'Chats',
      'you': 'You',
      'direct_messages': 'Direct Messages',
      'search_chats_hint': 'Search chats by name...',
      'clear': 'Clear',
      'new_group': 'New group',
      'settings': 'Settings',
      'no_chats_yet': 'No chats yet. Tap + to start one.',
      'you_cannot_chat_with_yourself': 'You cannot chat with yourself.',
      'could_not_create_chat': 'Could not create chat: {{error}}',
      'search_user': 'Search User',
      'search_by_name_or_username': 'Search by name or username',
      'no_users_available': 'No users available.',
      'no_matching_users_found': 'No matching users found.',
      'profile': 'Profile',
      'user_not_found': 'User not found',
      'online': 'Online',
      'offline': 'Offline',
      'last_seen': 'Last seen {{time}}',
      'contact_information': 'Contact Information',
      'send_message': 'Send Message',
      'block_account': 'Block account',
      'unblock_account': 'Unblock account',
      'block_account_confirm_title': 'Block account?',
      'block_account_confirm_body':
          'You will no longer see this account\'s posts or replies.',
      'unblock_account_confirm_title': 'Unblock account?',
      'unblock_account_confirm_body':
          'This account\'s posts and replies will be visible again.',
      'account_blocked': 'Account blocked',
      'account_unblocked': 'Account unblocked',
      'blocked_user_chat_not_allowed':
          'You have blocked this account. Unblock to start chatting.',
      'login_activity': 'Login Activity',
      'login_activity_description':
          'See the devices signed in to your account and revoke access from any of them.',
      'current_device': 'Current device',
      'last_active': 'Last active',
      'log_out_device': 'Log out device',
      'confirm_logout_device_title': 'Log out device?',
      'confirm_logout_device_body': 'This device will be signed out remotely.',
      'device_logged_out': 'Device logged out',
      'no_active_sessions': 'No active login sessions found.',
      'minutes_ago': '{{count}}m ago',
      'hours_ago': '{{count}}h ago',
      'days_ago': '{{count}}d ago',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'update_password': 'Update Password',
      'password_change_only_email_accounts':
          'Password change is only available for email/password accounts.',
      'no_account_email_found': 'No account email found for this user.',
      'please_enter_current_password': 'Please enter current password.',
      'new_password_min_6': 'New password must be at least 6 characters.',
      'new_password_mismatch': 'New passwords do not match.',
      'password_updated_successfully': 'Password updated successfully.',
      'password_update_failed': 'Failed to update password.',
      'current_password_incorrect': 'Current password is incorrect.',
      'choose_stronger_password': 'Please choose a stronger password.',
      'login_again_change_password':
          'Please log in again and try changing password.',
      'bio': 'Bio',
      'bio_too_long': 'Bio must be 200 characters or less.',
      'posts': 'Posts',
      'no_posts_yet': 'has no posts yet.',
      'settings_account': 'Account',
      'not_available': 'Not available',
      'edit_profile': 'Edit Profile',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'receive_message_notifications': 'Receive message notifications',
      'sound': 'Sound',
      'play_notification_sound': 'Play notification sound',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'select_theme': 'Select Theme',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'select_language': 'Select Language',
      'privacy': 'Privacy',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'message_read': 'Message Read',
      'read_receipt': 'Read receipt:',
      'close': 'Close',
      'back': 'Back',
      'delete': 'Delete',
      'delete_for_me': 'Delete for me',
      'delete_for_everyone': 'Delete for everyone',
      'message_deleted': 'Message deleted',
      'star': 'Star',
      'unstar': 'Unstar',
      'message_options': 'Message options',
      'failed_to_send_message': 'Failed to send message: {{error}}',
      'failed_to_send_image': 'Failed to send image: {{error}}',
      'direct_message': 'Direct Message',
      'what_is_on_your_mind': 'What is on your mind?',
      'typing': 'typing...',
      'type_a_message': 'Type a message...',
      'error': 'Error: {{error}}',
      'please_sign_in_view_messages': 'Please sign in to view messages.',
      'no_messages_yet': 'No messages yet.',
      'no_messages_start': 'No messages yet. Start the conversation.',
      'call_ended': 'Call ended',
      'no_phone_number_found': 'No phone number found for this contact',
      'opening_dialer_for': 'Opening dialer for {{phone}}',
      'could_not_open_dialer': 'Could not open the dialer',
      'new_group_title': 'New Group',
      'add_members': 'Add members',
      'create_group': 'Create Group',
      'group_name_empty': 'Group name cannot be empty',
      'group_created': 'Group created',
      'failed_create_group': 'Failed to create group: {{error}}',
      'email_change_requested': 'Email change requested',
      'ok': 'OK',
      'profile_updated': 'Profile updated',
      'failed_save_profile': 'Failed to save profile: {{error}}',
      'profile_picture_updated': 'Profile picture updated successfully',
      'failed_upload_profile_picture': 'Failed to upload profile picture',
      'save': 'Save',
      'selected_language_changed': 'Language changed to {{language}}',
      'show_now': 'Show Now',
      'scheduled_in_5_seconds': 'Scheduled in 5 seconds',
      'schedule_5s': 'Schedule (5s)',
      'no_users_to_call': 'No other users to call',
      'select_contact_to_call': 'Select Contact to Call',
      'no_users_found': 'No users found',
      'something_went_wrong': 'Something went wrong',
      'classmate': 'Classmate',
      'recent_notifications': 'Recent Notifications',
      'title': 'Title',
      'body': 'Body',
      'just_now': 'Just now',
      'unknown_user': 'Unknown User',
      'no_phone_number_added': 'No phone number added',
      'phone': 'Phone',
      'call_with': 'Call with {{name}}',
      'end_call': 'End Call',
      'open_dialer': 'Open Dialer',
      'opens_phone_dialer_using_saved_contact':
          'This opens the phone dialer using the saved contact number.',
      'email_change_info':
          'We saved your requested email. To complete an email change you may need to re-authenticate (sign out and sign in) or perform the change from your account settings.',
      'communities_placeholder': 'Communities placeholder',
      'username': 'Username',
      'please_enter_name': 'Please enter your name',
      'please_enter_username': 'Please enter a username',
      'username_min_3': 'Username must be at least 3 characters',
      'please_enter_email': 'Please enter an email',
      'enter_valid_email': 'Enter a valid email',
      'username_validation_error':
          'Username can only use letters, numbers, and underscores. Underscores cannot be first or last.',
      'username_login_firestore_error':
          'Username login needs Firestore read access. Temporarily log in with email, or update rules for username lookup.',
    },
    'es': {
      'app_name': 'Classmate',
      'continue': 'Continuar',
      'welcome_back': 'Bienvenido de nuevo',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'login': 'Iniciar sesión',
      'signup_prompt': '¿No tienes una cuenta? Regístrate',
      'create_account': 'Crea tu cuenta',
      'full_name': 'Nombre completo',
      'sign_up': 'Regístrate',
      'signup_successful': 'Registro exitoso',
      'updates': 'Actualizaciones',
      'calls': 'Llamadas',
      'communities': 'Comunidades',
      'chats': 'Chats',
      'you': 'Tú',
      'direct_messages': 'Mensajes Directos',
      'search_chats_hint': 'Buscar chats por nombre...',
      'clear': 'Borrar',
      'new_group': 'Nuevo grupo',
      'settings': 'Ajustes',
      'no_chats_yet': 'No hay chats. Pulsa + para empezar uno.',
      'you_cannot_chat_with_yourself': 'No puedes chatear contigo mismo.',
      'could_not_create_chat': 'No se pudo crear el chat: {{error}}',
      'search_user': 'Buscar usuario',
      'search_by_name_or_username': 'Buscar por nombre o usuario',
      'no_users_available': 'No hay usuarios disponibles.',
      'no_matching_users_found': 'No se encontraron usuarios coincidentes.',
      'profile': 'Perfil',
      'user_not_found': 'Usuario no encontrado',
      'online': 'En línea',
      'offline': 'Sin conexión',
      'last_seen': 'Última vez {{time}}',
      'contact_information': 'Información de contacto',
      'send_message': 'Enviar mensaje',
      'login_activity': 'Actividad de inicio de sesión',
      'login_activity_description':
          'Consulta los dispositivos conectados a tu cuenta y revoca el acceso de cualquiera de ellos.',
      'current_device': 'Dispositivo actual',
      'last_active': 'Última actividad',
      'log_out_device': 'Cerrar sesión del dispositivo',
      'confirm_logout_device_title': '¿Cerrar sesión del dispositivo?',
      'confirm_logout_device_body':
          'Este dispositivo se cerrará de sesión de forma remota.',
      'device_logged_out': 'Dispositivo cerrado de sesión',
      'no_active_sessions': 'No se encontraron sesiones activas.',
      'minutes_ago': 'hace {{count}} min',
      'hours_ago': 'hace {{count}} h',
      'days_ago': 'hace {{count}} días',
      'change_password': 'Cambiar contraseña',
      'current_password': 'Contraseña actual',
      'new_password': 'Nueva contraseña',
      'confirm_new_password': 'Confirmar nueva contraseña',
      'update_password': 'Actualizar contraseña',
      'password_change_only_email_accounts':
          'El cambio de contraseña solo está disponible para cuentas con correo y contraseña.',
      'no_account_email_found':
          'No se encontró un correo de cuenta para este usuario.',
      'please_enter_current_password': 'Ingresa la contraseña actual.',
      'new_password_min_6':
          'La nueva contraseña debe tener al menos 6 caracteres.',
      'new_password_mismatch': 'Las nuevas contraseñas no coinciden.',
      'password_updated_successfully': 'Contraseña actualizada con éxito.',
      'password_update_failed': 'No se pudo actualizar la contraseña.',
      'current_password_incorrect': 'La contraseña actual es incorrecta.',
      'choose_stronger_password': 'Elige una contraseña más segura.',
      'login_again_change_password':
          'Inicia sesión nuevamente e intenta cambiar la contraseña.',
      'bio': 'Biografía',
      'bio_too_long': 'La biografía debe tener 200 caracteres o menos.',
      'posts': 'Publicaciones',
      'no_posts_yet': 'no tiene publicaciones aún.',
      'settings_account': 'Cuenta',
      'not_available': 'No disponible',
      'edit_profile': 'Editar perfil',
      'notifications': 'Notificaciones',
      'enable_notifications': 'Activar notificaciones',
      'receive_message_notifications': 'Recibir notificaciones de mensajes',
      'sound': 'Sonido',
      'play_notification_sound': 'Reproducir sonido de notificación',
      'appearance': 'Apariencia',
      'theme': 'Tema',
      'select_theme': 'Seleccionar tema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',
      'privacy': 'Privacidad',
      'privacy_policy': 'Política de privacidad',
      'terms_of_service': 'Términos de servicio',
      'logout': 'Cerrar sesión',
      'logout_confirm': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'message_read': 'Mensaje leído',
      'read_receipt': 'Recibo de lectura:',
      'close': 'Cerrar',
      'back': 'Atrás',
      'delete': 'Eliminar',
      'delete_for_me': 'Eliminar para mí',
      'delete_for_everyone': 'Eliminar para todos',
      'message_deleted': 'Mensaje eliminado',
      'star': 'Favorito',
      'unstar': 'Quitar favorito',
      'message_options': 'Opciones de mensaje',
      'failed_to_send_message': 'No se pudo enviar el mensaje: {{error}}',
      'failed_to_send_image': 'No se pudo enviar la imagen: {{error}}',
      'direct_message': 'Mensaje directo',
      'what_is_on_your_mind': '¿Qué estás pensando?',
      'typing': 'escribiendo...',
      'type_a_message': 'Escribe un mensaje...',
      'error': 'Error: {{error}}',
      'please_sign_in_view_messages':
          'Por favor inicia sesión para ver los mensajes.',
      'no_messages_yet': 'Sin mensajes aún.',
      'no_messages_start': 'Sin mensajes aún. Empieza la conversación.',
      'call_ended': 'Llamada finalizada',
      'no_phone_number_found':
          'No se encontró número telefónico para este contacto',
      'opening_dialer_for': 'Abriendo marcador para {{phone}}',
      'could_not_open_dialer': 'No se pudo abrir el marcador',
      'new_group_title': 'Nuevo grupo',
      'add_members': 'Agregar miembros',
      'create_group': 'Crear grupo',
      'group_name_empty': 'El nombre del grupo no puede estar vacío',
      'group_created': 'Grupo creado',
      'failed_create_group': 'Error al crear el grupo: {{error}}',
      'email_change_requested': 'Cambio de correo solicitado',
      'ok': 'OK',
      'profile_updated': 'Perfil actualizado',
      'failed_save_profile': 'Error al guardar perfil: {{error}}',
      'profile_picture_updated': 'Foto de perfil actualizada con éxito',
      'failed_upload_profile_picture': 'Error al subir la foto de perfil',
      'save': 'Guardar',
      'selected_language_changed': 'Idioma cambiado a {{language}}',
      'show_now': 'Mostrar ahora',
      'scheduled_in_5_seconds': 'Programado en 5 segundos',
      'schedule_5s': 'Programar (5s)',
      'no_users_to_call': 'No hay otros usuarios para llamar',
      'select_contact_to_call': 'Seleccionar contacto para llamar',
      'no_users_found': 'No se encontraron usuarios',
      'something_went_wrong': 'Algo salió mal',
      'classmate': 'Classmate',
      'recent_notifications': 'Notificaciones recientes',
      'title': 'Título',
      'body': 'Cuerpo',
      'just_now': 'Hace poco',
      'unknown_user': 'Usuario desconocido',
      'no_phone_number_added': 'Sin número de teléfono añadido',
      'phone': 'Teléfono',
      'call_with': 'Llamada con {{name}}',
      'end_call': 'Finalizar llamada',
      'open_dialer': 'Abrir marcador',
      'opens_phone_dialer_using_saved_contact':
          'Abre el marcador telefónico usando el número de contacto guardado.',
      'email_change_info':
          'Hemos guardado el correo solicitado. Para completar un cambio de correo, puede que necesites re-autenticarte (cerrar y volver a iniciar sesión) o realizar el cambio desde tu configuración de cuenta.',
      'communities_placeholder': 'Placeholder de comunidades',
      'username': 'Nombre de usuario',
      'please_enter_name': 'Por favor ingresa tu nombre',
      'please_enter_username': 'Por favor ingresa un nombre de usuario',
      'username_min_3': 'El nombre de usuario debe tener al menos 3 caracteres',
      'please_enter_email': 'Por favor ingresa un correo electrónico',
      'enter_valid_email': 'Ingresa un correo electrónico válido',
      'username_validation_error':
          'El nombre de usuario solo puede usar letras, números y guiones bajos. Los guiones bajos no pueden estar al principio ni al final.',
      'username_login_firestore_error':
          'El inicio de sesión con nombre de usuario necesita acceso de lectura a Firestore. Inicia sesión temporalmente con correo electrónico o actualiza las reglas para la búsqueda de nombre de usuario.',
    },
    'zh': {
      'app_name': 'Classmate',
      'feed': '动态',
      'calls': '通话',
      'communities': '社区',
      'chats': '聊天',
      'you': '你',
      'continue': '继续',
      'welcome_back': '欢迎回来',
      'email': '电子邮件',
      'password': '密码',
      'login': '登录',
      'signup_prompt': '还没有账户？注册',
      'create_account': '创建你的账户',
      'full_name': '全名',
      'sign_up': '注册',
      'settings': '设置',
      'new_group': '新群组',
      'search_user': '搜索用户',
      'search_by_name_or_username': '按姓名或用户名搜索',
      'search_chats_hint': '按名称搜索聊天...',
      'direct_messages': '直接消息',
      'what_is_on_your_mind': '你在想什么？',
      'clear': '清除',
      'no_chats_yet': '还没有聊天。点击 + 开始一个。',
      'no_users_available': '没有可用用户。',
      'no_matching_users_found': '没有找到匹配的用户。',
      'settings_account': '账户',
      'not_available': '不可用',
      'edit_profile': '编辑资料',
      'notifications': '通知',
      'enable_notifications': '启用通知',
      'receive_message_notifications': '接收消息通知',
      'sound': '声音',
      'play_notification_sound': '播放通知声音',
      'appearance': '外观',
      'theme': '主题',
      'select_theme': '选择主题',
      'light': '浅色',
      'dark': '深色',
      'language': '语言',
      'select_language': '选择语言',
      'privacy': '隐私',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'logout': '退出登录',
      'logout_confirm': '确定要退出登录吗？',
      'cancel': '取消',
      'profile': '个人资料',
      'user_not_found': '未找到用户',
      'online': '在线',
      'offline': '离线',
      'last_seen': '上次在线 {{time}}',
      'contact_information': '联系信息',
      'send_message': '发送消息',
      'login_activity': '登录活动',
      'login_activity_description': '查看已登录到你账户的设备，并可撤销任一设备的访问权限。',
      'current_device': '当前设备',
      'last_active': '最后活动',
      'log_out_device': '退出该设备',
      'confirm_logout_device_title': '退出设备？',
      'confirm_logout_device_body': '此设备将被远程注销。',
      'device_logged_out': '设备已注销',
      'no_active_sessions': '未找到活跃的登录会话。',
      'just_now': '刚刚',
      'minutes_ago': '{{count}} 分钟前',
      'hours_ago': '{{count}} 小时前',
      'days_ago': '{{count}} 天前',
      'change_password': '更改密码',
      'current_password': '当前密码',
      'new_password': '新密码',
      'confirm_new_password': '确认新密码',
      'update_password': '更新密码',
      'password_change_only_email_accounts': '仅支持邮箱/密码账户修改密码。',
      'no_account_email_found': '未找到该用户的账户邮箱。',
      'please_enter_current_password': '请输入当前密码。',
      'new_password_min_6': '新密码至少需要 6 个字符。',
      'new_password_mismatch': '两次输入的新密码不一致。',
      'password_updated_successfully': '密码更新成功。',
      'password_update_failed': '密码更新失败。',
      'current_password_incorrect': '当前密码不正确。',
      'choose_stronger_password': '请选择更强的密码。',
      'login_again_change_password': '请重新登录后再尝试修改密码。',
      'bio': '简介',
      'bio_too_long': '简介必须少于或等于 200 个字符。',
      'posts': '帖子',
      'no_posts_yet': '还没有帖子。',
      'call_ended': '通话已结束',
      'no_phone_number_found': '此联系人未找到电话号码',
      'opening_dialer_for': '正在打开拨号器拨打 {{phone}}',
      'could_not_open_dialer': '无法打开拨号器',
      'no_users_to_call': '没有其他用户可以调用',
      'select_contact_to_call': '选择要呼叫的联系人',
      'unknown_user': '未知用户',
      'no_phone_number_added': '未添加电话号码',
      'phone': '电话',
      'call_with': '与 {{name}} 通话',
      'end_call': '结束通话',
      'open_dialer': '打开拨号器',
      'opens_phone_dialer_using_saved_contact': '这将使用保存的联系人号码打开电话拨号器。',
      'save': '保存',
      'selected_language_changed': '语言已切换为 {{language}}',
      'please_enter_name': '请输入你的姓名',
      'please_enter_username': '请输入用户名',
      'username_min_3': '用户名至少需要 3 个字符',
      'please_enter_email': '请输入电子邮箱',
      'enter_valid_email': '请输入有效的电子邮箱',
    },
    'hi': {
      'app_name': 'Classmate',
      'feed': 'फीड',
      'calls': 'कॉल',
      'communities': 'समुदाय',
      'chats': 'चैट',
      'you': 'आप',
      'continue': 'जारी रखें',
      'welcome_back': 'वापसी पर स्वागत है',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'login': 'लॉगिन करें',
      'signup_prompt': 'खाता नहीं है? साइन अप करें',
      'create_account': 'अपना खाता बनाएं',
      'full_name': 'पूरा नाम',
      'sign_up': 'साइन अप करें',
      'signup_successful': 'साइन अप सफल',
      'updates': 'अपडेट',
      'settings': 'सेटिंग्स',
      'new_group': 'नया समूह',
      'search_user': 'उपयोगकर्ता खोजें',
      'search_by_name_or_username': 'नाम या उपयोगकर्ता नाम से खोजें',
      'search_chats_hint': 'नाम से चैट खोजें...',
      'direct_messages': 'सीधे संदेश',
      'what_is_on_your_mind': 'आपके मन में क्या है?',
      'clear': 'साफ करें',
      'no_chats_yet': 'अभी तक कोई चैट नहीं। शुरू करने के लिए + टैप करें।',
      'you_cannot_chat_with_yourself': 'आप अपने आप से चैट नहीं कर सकते।',
      'could_not_create_chat': 'चैट नहीं बना सके: {{error}}',
      'no_users_available': 'कोई उपयोगकर्ता उपलब्ध नहीं।',
      'no_matching_users_found': 'कोई मेल खाने वाले उपयोगकर्ता नहीं मिले।',
      'settings_account': 'खाता',
      'not_available': 'उपलब्ध नहीं',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'receive_message_notifications': 'संदेश सूचनाएं प्राप्त करें',
      'sound': 'ध्वनि',
      'play_notification_sound': 'सूचना ध्वनि चलाएं',
      'appearance': 'दिखावट',
      'theme': 'थीम',
      'select_theme': 'थीम चुनें',
      'light': 'हल्का',
      'dark': 'गहरा',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'privacy': 'गोपनीयता',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_service': 'सेवा की शर्तें',
      'logout': 'लॉगआउट करें',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'profile': 'प्रोफ़ाइल',
      'user_not_found': 'उपयोगकर्ता नहीं मिला',
      'online': 'ऑनलाइन',
      'offline': 'ऑफ़लाइन',
      'last_seen': 'आखिरी बार {{time}} को देखा गया',
      'contact_information': 'संपर्क जानकारी',
      'send_message': 'संदेश भेजें',
      'login_activity': 'लॉगिन गतिविधि',
      'login_activity_description':
          'अपने खाते में साइन इन किए गए डिवाइस देखें और किसी भी डिवाइस की पहुँच रद्द करें।',
      'current_device': 'वर्तमान डिवाइस',
      'last_active': 'अंतिम गतिविधि',
      'log_out_device': 'डिवाइस से लॉग आउट करें',
      'confirm_logout_device_title': 'डिवाइस से लॉग आउट करें?',
      'confirm_logout_device_body': 'यह डिवाइस दूर से साइन आउट हो जाएगा।',
      'device_logged_out': 'डिवाइस लॉग आउट हो गया',
      'no_active_sessions': 'कोई सक्रिय लॉगिन सत्र नहीं मिला।',
      'minutes_ago': '{{count}} मिनट पहले',
      'hours_ago': '{{count}} घंटे पहले',
      'days_ago': '{{count}} दिन पहले',
      'change_password': 'पासवर्ड बदलें',
      'current_password': 'वर्तमान पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
      'update_password': 'पासवर्ड अपडेट करें',
      'password_change_only_email_accounts':
          'पासवर्ड बदलना केवल ईमेल/पासवर्ड खातों के लिए उपलब्ध है।',
      'no_account_email_found': 'इस उपयोगकर्ता के लिए खाता ईमेल नहीं मिला।',
      'please_enter_current_password': 'कृपया वर्तमान पासवर्ड दर्ज करें।',
      'new_password_min_6': 'नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'new_password_mismatch': 'नए पासवर्ड मेल नहीं खाते।',
      'password_updated_successfully': 'पासवर्ड सफलतापूर्वक अपडेट हो गया।',
      'password_update_failed': 'पासवर्ड अपडेट करने में विफल।',
      'current_password_incorrect': 'वर्तमान पासवर्ड गलत है।',
      'choose_stronger_password': 'कृपया अधिक मजबूत पासवर्ड चुनें।',
      'login_again_change_password':
          'कृपया फिर से लॉग इन करें और पासवर्ड बदलने का प्रयास करें।',
      'bio': 'बायो',
      'bio_too_long': 'बायो 200 अक्षरों या उससे कम होना चाहिए।',
      'posts': 'पोस्ट',
      'no_posts_yet': 'के पास अभी तक कोई पोस्ट नहीं है।',
      'message_read': 'संदेश पढ़ा गया',
      'read_receipt': 'पढ़ने की रसीद:',
      'close': 'बंद करें',
      'back': 'पीछे',
      'delete': 'हटाएं',
      'delete_for_me': 'मेरे लिए हटाएं',
      'delete_for_everyone': 'सभी के लिए हटाएं',
      'message_deleted': 'संदेश हटाया गया',
      'star': 'पसंद करें',
      'unstar': 'पसंद न करें',
      'message_options': 'संदेश विकल्प',
      'failed_to_send_message': 'संदेश भेजने में विफल: {{error}}',
      'failed_to_send_image': 'छवि भेजने में विफल: {{error}}',
      'direct_message': 'सीधा संदेश',
      'typing': 'टाइप कर रहा है...',
      'type_a_message': 'संदेश लिखें...',
      'error': 'त्रुटि: {{error}}',
      'please_sign_in_view_messages': 'संदेश देखने के लिए कृपया साइन इन करें।',
      'no_messages_yet': 'अभी तक कोई संदेश नहीं।',
      'no_messages_start': 'अभी तक कोई संदेश नहीं। बातचीत शुरू करें।',
      'call_ended': 'कॉल समाप्त हुई',
      'no_phone_number_found': 'इस संपर्क के लिए कोई फोन नंबर नहीं मिला',
      'opening_dialer_for': '{{phone}} के लिए डायलर खोल रहे हैं',
      'could_not_open_dialer': 'डायलर नहीं खोल सके',
      'new_group_title': 'नया समूह',
      'add_members': 'सदस्य जोड़ें',
      'create_group': 'समूह बनाएं',
      'group_name_empty': 'समूह का नाम खाली नहीं हो सकता',
      'group_created': 'समूह बनाया गया',
      'failed_create_group': 'समूह बनाने में विफल: {{error}}',
      'email_change_requested': 'ईमेल परिवर्तन का अनुरोध किया गया',
      'ok': 'ठीक है',
      'profile_updated': 'प्रोफ़ाइल अपडेट की गई',
      'failed_save_profile': 'प्रोफ़ाइल सहेजने में विफल: {{error}}',
      'profile_picture_updated': 'प्रोफ़ाइल चित्र सफलतापूर्वक अपडेट किया गया',
      'failed_upload_profile_picture': 'प्रोफ़ाइल चित्र अपलोड करने में विफल',
      'save': 'सहेजें',
      'selected_language_changed': 'भाषा {{language}} में बदली गई',
      'show_now': 'अभी दिखाएं',
      'scheduled_in_5_seconds': '5 सेकंड में शेड्यूल किया गया',
      'schedule_5s': 'शेड्यूल (5s)',
      'no_users_to_call': 'कॉल करने के लिए कोई अन्य उपयोगकर्ता नहीं',
      'select_contact_to_call': 'कॉल करने के लिए संपर्क चुनें',
      'no_users_found': 'कोई उपयोगकर्ता नहीं मिला',
      'something_went_wrong': 'कुछ गलत हो गया',
      'classmate': 'Classmate',
      'recent_notifications': 'हाल की सूचनाएं',
      'title': 'शीर्षक',
      'body': 'निकाय',
      'just_now': 'अभी ही',
      'unknown_user': 'अज्ञात उपयोगकर्ता',
      'no_phone_number_added': 'कोई फोन नंबर जोड़ा नहीं गया',
      'phone': 'फोन',
      'call_with': '{{name}} के साथ कॉल करें',
      'end_call': 'कॉल समाप्त करें',
      'open_dialer': 'डायलर खोलें',
      'opens_phone_dialer_using_saved_contact':
          'यह सहेजे गए संपर्क नंबर का उपयोग करके फोन डायलर खोलता है।',
      'email_change_info':
          'हमने आपके अनुरोधित ईमेल को सहेज लिया है। ईमेल परिवर्तन को पूरा करने के लिए आपको पुनः प्रमाणित करने की आवश्यकता हो सकती है (साइन आउट और साइन इन करें) या अपनी खाता सेटिंग्स से परिवर्तन करें।',
      'communities_placeholder': 'समुदाय प्लेसहोल्डर',
      'username': 'उपयोगकर्ता नाम',
      'please_enter_name': 'कृपया अपना नाम दर्ज करें',
      'please_enter_username': 'कृपया उपयोगकर्ता नाम दर्ज करें',
      'username_min_3': 'उपयोगकर्ता नाम कम से कम 3 अक्षरों का होना चाहिए',
      'please_enter_email': 'कृपया ईमेल दर्ज करें',
      'enter_valid_email': 'मान्य ईमेल दर्ज करें',
      'username_validation_error':
          'उपयोगकर्ता नाम केवल अक्षर, संख्या और अंडरस्कोर का उपयोग कर सकता है। अंडरस्कोर पहला या आखिरी नहीं हो सकता।',
      'username_login_firestore_error':
          'उपयोगकर्ता नाम लॉगिन को Firestore पढ़ने की पहुंच की आवश्यकता है। अस्थायी रूप से ईमेल के साथ लॉगिन करें या उपयोगकर्ता नाम खोज के लिए नियम अपडेट करें।',
    },
    'fr': {
      'app_name': 'Classmate',
      'feed': 'Fil',
      'calls': 'Appels',
      'communities': 'Communautés',
      'chats': 'Chats',
      'you': 'Vous',
      'continue': 'Continuer',
      'welcome_back': 'Bon retour',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'login': 'Se connecter',
      'signup_prompt': "Vous n'avez pas de compte ? Inscrivez-vous",
      'create_account': 'Créez votre compte',
      'full_name': 'Nom complet',
      'sign_up': "S'inscrire",
      'signup_successful': "Inscription réussie",
      'updates': 'Mises à jour',
      'direct_messages': 'Messages directs',
      'what_is_on_your_mind': 'À quoi pensez-vous ?',
      'search_chats_hint': 'Rechercher des discussions par nom...',
      'clear': 'Effacer',
      'new_group': 'Nouveau groupe',
      'settings': 'Paramètres',
      'no_chats_yet':
          'Aucune discussion pour le moment. Appuyez sur + pour en commencer une.',
      'you_cannot_chat_with_yourself':
          'Vous ne pouvez pas discuter avec vous-même.',
      'could_not_create_chat': 'Impossible de créer la discussion : {{error}}',
      'search_user': 'Rechercher un utilisateur',
      'search_by_name_or_username': 'Rechercher par nom ou nom d’utilisateur',
      'no_users_available': 'Aucun utilisateur disponible.',
      'no_matching_users_found': 'Aucun utilisateur correspondant trouvé.',
      'profile': 'Profil',
      'user_not_found': 'Utilisateur introuvable',
      'online': 'En ligne',
      'offline': 'Hors ligne',
      'last_seen': 'Vu pour la dernière fois {{time}}',
      'contact_information': 'Informations de contact',
      'send_message': 'Envoyer un message',
      'login_activity': 'Activité de connexion',
      'login_activity_description':
          'Voir les appareils connectés à votre compte et révoquer l’accès de n’importe lequel d’entre eux.',
      'current_device': 'Appareil actuel',
      'last_active': 'Dernière activité',
      'log_out_device': 'Déconnecter l’appareil',
      'confirm_logout_device_title': 'Déconnecter l’appareil ?',
      'confirm_logout_device_body': 'Cet appareil sera déconnecté à distance.',
      'device_logged_out': 'Appareil déconnecté',
      'no_active_sessions': 'Aucune session active trouvée.',
      'minutes_ago': 'il y a {{count}} min',
      'hours_ago': 'il y a {{count}} h',
      'days_ago': 'il y a {{count}} j',
      'change_password': 'Changer le mot de passe',
      'current_password': 'Mot de passe actuel',
      'new_password': 'Nouveau mot de passe',
      'confirm_new_password': 'Confirmer le nouveau mot de passe',
      'update_password': 'Mettre à jour le mot de passe',
      'password_change_only_email_accounts':
          'Le changement de mot de passe est uniquement disponible pour les comptes e-mail/mot de passe.',
      'no_account_email_found':
          'Aucun e-mail de compte trouvé pour cet utilisateur.',
      'please_enter_current_password':
          'Veuillez saisir le mot de passe actuel.',
      'new_password_min_6':
          'Le nouveau mot de passe doit contenir au moins 6 caractères.',
      'new_password_mismatch':
          'Les nouveaux mots de passe ne correspondent pas.',
      'password_updated_successfully': 'Mot de passe mis à jour avec succès.',
      'password_update_failed': 'Échec de la mise à jour du mot de passe.',
      'current_password_incorrect': 'Le mot de passe actuel est incorrect.',
      'choose_stronger_password': 'Veuillez choisir un mot de passe plus fort.',
      'login_again_change_password':
          'Veuillez vous reconnecter puis réessayer de changer le mot de passe.',
      'bio': 'Bio',
      'bio_too_long': 'La bio doit comporter 200 caractères maximum.',
      'posts': 'Messages',
      'no_posts_yet': "n'a pas encore de messages.",
      'settings_account': 'Compte',
      'not_available': 'Indisponible',
      'edit_profile': 'Modifier le profil',
      'notifications': 'Notifications',
      'enable_notifications': 'Activer les notifications',
      'receive_message_notifications': 'Recevoir les notifications de message',
      'sound': 'Son',
      'play_notification_sound': 'Lire le son de notification',
      'appearance': 'Apparence',
      'theme': 'Thème',
      'select_theme': 'Sélectionner le thème',
      'light': 'Clair',
      'dark': 'Sombre',
      'language': 'Langue',
      'select_language': 'Sélectionner la langue',
      'privacy': 'Confidentialité',
      'privacy_policy': 'Politique de confidentialité',
      'terms_of_service': 'Conditions d’utilisation',
      'logout': 'Se déconnecter',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'cancel': 'Annuler',
      'message_read': 'Message lu',
      'read_receipt': 'Accusé de lecture :',
      'close': 'Fermer',
      'back': 'Retour',
      'delete': 'Supprimer',
      'delete_for_me': 'Supprimer pour moi',
      'delete_for_everyone': 'Supprimer pour tout le monde',
      'message_deleted': 'Message supprimé',
      'star': 'Favori',
      'unstar': 'Retirer des favoris',
      'message_options': 'Options du message',
      'failed_to_send_message': 'Échec de l’envoi du message : {{error}}',
      'failed_to_send_image': 'Échec de l’envoi de l’image : {{error}}',
      'direct_message': 'Message direct',
      'typing': 'en train d’écrire...',
      'type_a_message': 'Tapez un message...',
      'error': 'Erreur : {{error}}',
      'please_sign_in_view_messages':
          'Veuillez vous connecter pour voir les messages.',
      'no_messages_yet': 'Aucun message pour le moment.',
      'no_messages_start':
          'Aucun message pour le moment. Commencez la conversation.',
      'call_ended': 'Appel terminé',
      'no_phone_number_found':
          'Aucun numéro de téléphone trouvé pour ce contact',
      'opening_dialer_for': 'Ouverture du composeur pour {{phone}}',
      'could_not_open_dialer': 'Impossible d’ouvrir le composeur',
      'new_group_title': 'Nouveau groupe',
      'add_members': 'Ajouter des membres',
      'create_group': 'Créer le groupe',
      'group_name_empty': 'Le nom du groupe ne peut pas être vide',
      'group_created': 'Groupe créé',
      'failed_create_group': 'Échec de la création du groupe : {{error}}',
      'email_change_requested': 'Changement d’e-mail demandé',
      'ok': 'OK',
      'profile_updated': 'Profil mis à jour',
      'failed_save_profile': 'Échec de l’enregistrement du profil : {{error}}',
      'profile_picture_updated': 'Photo de profil mise à jour avec succès',
      'failed_upload_profile_picture':
          'Échec du téléversement de la photo de profil',
      'save': 'Enregistrer',
      'selected_language_changed': 'Langue changée en {{language}}',
      'show_now': 'Afficher maintenant',
      'scheduled_in_5_seconds': 'Planifié dans 5 secondes',
      'schedule_5s': 'Planifier (5 s)',
      'no_users_to_call': 'Aucun autre utilisateur à appeler',
      'select_contact_to_call': 'Sélectionner un contact à appeler',
      'no_users_found': 'Aucun utilisateur trouvé',
      'something_went_wrong': 'Quelque chose s’est mal passé',
      'classmate': 'Classmate',
      'recent_notifications': 'Notifications récentes',
      'title': 'Titre',
      'body': 'Contenu',
      'just_now': 'À l’instant',
      'unknown_user': 'Utilisateur inconnu',
      'no_phone_number_added': 'Aucun numéro de téléphone ajouté',
      'phone': 'Téléphone',
      'call_with': 'Appel avec {{name}}',
      'end_call': 'Terminer l’appel',
      'open_dialer': 'Ouvrir le composeur',
      'opens_phone_dialer_using_saved_contact':
          'Ouvre le composeur téléphonique en utilisant le numéro du contact enregistré.',
      'email_change_info':
          'Nous avons enregistré l’e-mail demandé. Pour terminer un changement d’e-mail, vous devrez peut-être vous réauthentifier (vous déconnecter puis vous reconnecter) ou effectuer le changement depuis les paramètres de votre compte.',
      'communities_placeholder': 'Espace réservé aux communautés',
      'username': 'Nom d’utilisateur',
      'please_enter_name': 'Veuillez saisir votre nom',
      'please_enter_username': 'Veuillez saisir un nom d’utilisateur',
      'username_min_3':
          'Le nom d’utilisateur doit contenir au moins 3 caractères',
      'please_enter_email': 'Veuillez saisir un e-mail',
      'enter_valid_email': 'Saisissez un e-mail valide',
      'username_validation_error':
          'Le nom d’utilisateur ne peut utiliser que des lettres, des chiffres et des underscores. Les underscores ne peuvent pas être au début ni à la fin.',
      'username_login_firestore_error':
          'La connexion par nom d’utilisateur nécessite un accès en lecture à Firestore. Connectez-vous temporairement avec l’e-mail ou mettez à jour les règles pour la recherche par nom d’utilisateur.',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    final map = _values[locale.languageCode] ?? _values['en']!;
    var value = map[key] ?? _values['en']![key] ?? key;
    params?.forEach((param, replacement) {
      value = value.replaceAll('{{$param}}', replacement);
    });
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'es', 'zh', 'hi', 'fr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
